# Generated by Django 5.0.3 on 2024-06-08 20:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cake_items', '0004_rename_flaver_cakemodel_flavor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cake_size', models.CharField(choices=[('1', 'Small (1kg)'), ('2', 'Medium (1.5kg)'), ('3', 'Large (2kg)')], max_length=100)),
                ('total_price', models.IntegerField()),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('shipped', 'Shipped'), ('delivered', 'Delivered')], default='processing', max_length=100)),
                ('cake', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cake_items.cakemodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
