# Generated by Django 5.0.3 on 2024-06-08 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cake_items', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cakemodel',
            name='cake_size',
        ),
    ]
