# Generated by Django 5.0.3 on 2024-06-08 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cake_items', '0002_remove_cakemodel_cake_size'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cakemodel',
            old_name='category',
            new_name='flaver',
        ),
        migrations.RemoveField(
            model_name='cakemodel',
            name='cake_name',
        ),
        migrations.AddField(
            model_name='cakemodel',
            name='cake_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
