# Generated by Django 5.0.3 on 2024-06-08 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cake_items', '0003_rename_category_cakemodel_flaver_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cakemodel',
            old_name='flaver',
            new_name='flavor',
        ),
    ]
